name: buildit
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - runjb
  - click
  - sphinx=2.4.4
  - jupyter
  - pip
  - pip:
    - git+https://github.com/executablebooks/jupyter-book




